#back/docker-compose.yml
version: '3.7'

services:
  backend:
    container_name: "koflowa_backend"
    image: koflowa_backend:0.1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8448:8081"
    # [인증서 파일 저장 경로]:/root
    volumes:
      - /etc/letsencrypt/live/k7d202.p.ssafy.io/:/root
    environment:
      - TZ=Asia/Seoul