spring:
  profiles:
    active: dev
    include: oauth,secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7d202.p.ssafy.io:5000/koflowa?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false

  redis:
    host: localhost
    port: 6379

  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  use-fqn: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC

server:
  servlet:
    context-path: /api
  port: 8081
  tomcat:
    max-http-form-post-size: 20MB
  max-http-header-size: 400000

logging:
  level:
    #    root: debug
    org.hibernate.SQL: debug
    org.springframework.web: debug
    #    org.hibernate.type: trace
    com.d202.koflowa: debug

app:
  auth:
  oauth2:
    authorized-redirect-uris: "http://localhost:3000/nickname"
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
      - "http://localhost:8448"
      - "https://k7d202.p.ssafy.io"