spring:
  profiles:
    active: dev
    include: oauth,secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/koflowa?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  redis:
    cluster:
      nodes: k7d202.p.ssafy.io:6379,k7d202.p.ssafy.io:6380,k7d202.p.ssafy.io:6381
#    host: k7d202.p.ssafy.io
#    port: 6379

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    groups-order: DESC

server:
  servlet:
    context-path: /api
  port: 8081
  tomcat:
    max-http-form-post-size: 20MB

logging:
  level:
    #    root: debug
    org.hibernate.SQL: debug
    org.springframework.web: debug
    #    org.hibernate.type: trace
    com.d202.koflowa: debug

